import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { WhatsappLogo } from "phosphor-react";
import { useState } from "react";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";
import { Services } from "../components/Services";
import styles from "../styles/Home.module.css";

import About from "../components/Ads/About2";
import WorkNumbers from "../components/Ads/WorkNumbers";
import Advantages from "../components/Ads/Advantages";
import { url } from "inspector";

const AdsSolarGeneration: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Fótum Engenharia | Geração Solar</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <Header />

            <div
                id="hero"
                className="flex flex-col p-4 gap-8 mb-16 lg:max-w-[1400px] lg:mx-auto lg:px-24 "
            >
                <div className="flex flex-col gap-4 max-w-3xl">
                    <p className="text-xl lg:text-2xl">Fale com um</p>
                    <h2 className="text-5xl font-extrabold lg:text-7xl">
                        Engenheiro especialista em{" "}
                        <span className="text-[#ffaa00]">Geração Solar.</span>
                    </h2>
                    <p className="text-2xl max-w-[40ch]">
                        Receba agora um atendimento personalizado de um
                        engenheiro que atende a instalações de geração solar
                        todos os dias
                    </p>
                </div>

                <div className="flex flex-col gap-12">
                    <div className="flex flex-col gap-4 justify-start items-center sm:flex-row">
                        <a
                            href="https://wa.me/message/2KTISK2P7CG6E1"
                            target="_blank"
                            rel="noreferrer"
                            className="flex items-center gap-2 justify-center bg-green-500 font-bold py-3 px-6 rounded-3xl text-lg hover:bg-green-200 w-fit"
                        >
                            <WhatsappLogo size={28} />
                            <p>Falar com o engenheiro</p>
                        </a>
                        <a href="tel:48984110903" className="text-center">
                            (48) 98411-0903 - Florianópolis e Região
                        </a>
                    </div>
                    <a
                        // onClick={() =>
                        //     document.getElementsByClassName("work-numbers")
                        // }
                        // href={document.getElementsByClassName("work-numbers")!}
                        className="relative flex flex-col gap-2 justify-center items-center font-bold uppercase text-center text-xl"
                    >
                        <p>Ver mais</p>
                        <div className="chevron"></div>
                        <div className="chevron"></div>
                        <div className="chevron"></div>
                    </a>
                </div>
            </div>

            <WorkNumbers />
            <Advantages />
            <About />
            <Footer />
        </div>
    );
};

export default AdsSolarGeneration;
