import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AboutEngineer from "../components/Ads/AboutEngineer";
import Advantages from "../components/Ads/Advantages";
import WorkNumbers from "../components/Ads/WorkNumbers";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";
import { Services } from "../components/Services";
// import SolarDiagram from "../components/SolarDiagram";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Fótum Engenharia</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <div className="flex flex-col relative w-full">
                <div className="flex w-full items-center justify-center">
                    <Header />
                </div>

                <div className="flex flex-col mt-20  ">
                    <Hero />
                    <div className="mt-6 w-full bg-gray-200">
                        <WorkNumbers />
                    </div>

                    <Advantages />

                    <Services />
                    {/* <SolarDiagram /> */}
                    <AboutEngineer />

                    <Footer />
                </div>
            </div>
        </>
    );
};

export default Home;
